spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:5432/vcdb}
spring.datasource.username=${DATABASE_USER:vcuser}
spring.datasource.password=${DATABASE_PASSWORD:swt@2026}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
server.port=8080

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=elrhadiry1@gmail.com
spring.mail.password=lqzdlcwttycminlu
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

jwt.secret=ytjGl+ioZNPfKkv8U3U3hPzVJ1dcAga3NRpv8EtZ9fDilj2zLu8tN90m03qqkeIdm9fIv99k3p6GfOF/kDKamQ==
jwt.expiration-ms=86400000

logging.level.org.springframework.security=DEBUG

# mqtt.broker.url=${MQTT_URL:tcp://vc_mqtt:1883} 
mqtt.broker.url=tcp://localhost:1883
mqtt.client.id.backend=api-backend-subscriber-01
mqtt.topic.anmeldung=exams/registration/opened

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB

material.upload-dir=src/main/resources/uploads/materialien