FROM maven:3.9.9-eclipse-temurin-21 AS build

WORKDIR /workspace

COPY . .

RUN mvn clean package -pl daten-simulator -am -DskipTests

RUN cp daten-simulator/target/*.jar /tmp/app.jar

FROM eclipse-temurin:21-jre

WORKDIR /app

COPY --from=build /tmp/app.jar app.jar

EXPOSE 8081

ENTRYPOINT ["java","-jar","app.jar"]